const categoryInfo = {
  fundamentals:{title:'CS fundamentals',label:'CS FUNDAMENTALS',dot:'dot-lime',type:'Core concept',count:8},
  problem:{title:'Problem solving',label:'PROBLEM SOLVING',dot:'dot-coral',type:'Think it through',count:5},
  practical:{title:'Practical exposure',label:'PRACTICAL EXPOSURE',dot:'dot-blue',type:'Tell your story',count:5},
  behavioral:{title:'Behavioral fit',label:'BEHAVIORAL FIT',dot:'dot-lilac',type:'Your perspective',count:5}
};
const questions = [
 {id:'f1',category:'fundamentals',kind:'mcq',level:'Core concepts',question:'Which data structure gives you O(1) average-case lookup by key?',options:['A linked list','A hash table','A binary search tree (unbalanced)','A queue'],answer:1,explanation:'A hash table maps keys to buckets, giving average-case constant-time lookup. Collisions can make a lookup slower, so mention the average-case assumption.'},
 {id:'f2',category:'fundamentals',kind:'mcq',level:'Operating systems',question:'What is the key difference between a process and a thread?',options:['Threads have separate address spaces; processes share one','Processes share an address space; threads do not','Threads in one process share memory, while processes are isolated','There is no practical difference'],answer:2,explanation:'Threads within a process share its memory and resources, though each thread has its own stack and execution state. Separate processes have isolated address spaces.'},
 {id:'f3',category:'fundamentals',kind:'mcq',level:'Databases',question:'What is the main goal of normalization in a relational database?',options:['Make every query use an index','Reduce redundant data and prevent update anomalies','Encrypt sensitive columns','Store all records in one table'],answer:1,explanation:'Normalization organizes related data to reduce duplication and avoid insert, update, and delete anomalies. A well-designed schema balances this with query needs.'},
 {id:'f4',category:'fundamentals',kind:'mcq',level:'Computer networks',question:'When is UDP often a better fit than TCP?',options:['When every byte must be delivered in order','When low latency matters more than retransmitting every lost packet','When a connection must be established first','When transferring a file that must be complete'],answer:1,explanation:'UDP avoids connection setup and retransmission guarantees, which can suit real-time audio, video, and gaming where timeliness matters.'},
 {id:'f5',category:'fundamentals',kind:'mcq',level:'Object-oriented programming',question:'Which OOP idea lets a class expose a simple interface while hiding implementation details?',options:['Inheritance','Abstraction','Overloading','Compilation'],answer:1,explanation:'Abstraction presents the operations a caller needs while hiding internal details. Encapsulation controls access to an object’s state and behavior.'},
 {id:'f6',category:'fundamentals',kind:'mcq',level:'Data structures',question:'Which structure is most directly used to manage function calls and recursion?',options:['Queue','Stack','Heap','Graph'],answer:1,explanation:'Function calls are managed with a call stack. Each call adds a frame, and returning removes it in last-in, first-out order.'},
 {id:'f7',category:'fundamentals',kind:'mcq',level:'Operating systems',question:'Which set lists the four conditions traditionally required for deadlock?',options:['Paging, caching, scheduling, swapping','Mutual exclusion, hold and wait, no preemption, circular wait','Race condition, starvation, priority, interrupt','Atomicity, consistency, isolation, durability'],answer:1,explanation:'Deadlock requires all four Coffman conditions. Preventing any one of them can prevent deadlock; resource ordering is one common strategy.'},
 {id:'f8',category:'fundamentals',kind:'mcq',level:'Databases',question:'What is the main trade-off when adding a database index?',options:['Faster reads, with extra storage and slower writes','Faster writes, with extra storage and slower reads','No impact on writes or storage','It removes the need for primary keys'],answer:0,explanation:'Indexes can speed up filtering and joins, but use storage and must be updated on writes. Choose them based on query patterns.'},
 {id:'p1',category:'problem',kind:'mcq',level:'Algorithm design',question:'You need to detect whether a linked list has a cycle using O(1) extra space. Which approach fits?',options:['Store every visited node in a set','Sort the list','Use slow and fast pointers','Reverse the list twice'],answer:2,explanation:'Floyd’s tortoise-and-hare method uses two pointers moving at different speeds. They meet if a cycle exists, using O(n) time and O(1) extra space.'},
 {id:'p2',category:'problem',kind:'mcq',level:'Complexity',question:'A solution checks every pair in an array of n elements. What is its time complexity?',options:['O(1)','O(log n)','O(n)','O(n²)'],answer:3,explanation:'There are roughly n × n pairs to check, so the work grows quadratically. If pairs are only distinct pairs, the exact count is n(n−1)/2, still O(n²).'},
 {id:'p3',category:'problem',kind:'reflection',level:'Debugging',question:'A program passes the sample tests but fails on a few hidden cases. How would you investigate?',hint:'Think aloud as if you were pairing with an interviewer. Start with constraints, then describe how you would narrow down the failure.',prompts:['Clarify constraints','Reproduce the bug','Check edge cases','Explain your fix']},
 {id:'p4',category:'problem',kind:'reflection',level:'Coding approach',question:'You are asked to find two numbers in an array that add up to a target. Explain two approaches and how you would choose between them.',hint:'A strong answer names the straightforward approach first, then explains a more efficient option and its trade-offs.',prompts:['Brute force baseline','Time & space trade-off','Input assumptions','Test cases']},
 {id:'p5',category:'problem',kind:'reflection',level:'Problem solving',question:'During a coding interview, you realize your first approach is too slow. What do you do next?',hint:'Interviewers are interested in how you respond to new information, not only whether you started with the optimal solution.',prompts:['Acknowledge the constraint','Find repeated work','Propose an alternative','Verify the new approach']},
 {id:'x1',category:'practical',kind:'reflection',level:'Project deep dive',question:'Tell me about a project you built. What problem did it solve, what was your contribution, and what would you improve?',hint:'Make the story concrete. Focus on your own decisions and outcomes, rather than listing technologies.',prompts:['Context & goal','Your contribution','Challenge & outcome','What you learned']},
 {id:'x2',category:'practical',kind:'reflection',level:'Technical choices',question:'Pick a project from your portfolio. Why did you choose its tech stack, and what trade-off would you revisit?',hint:'Show that your choices matched the project’s needs. There is rarely one universally correct stack.',prompts:['Project constraints','Alternatives considered','Trade-off','What you would change']},
 {id:'x3',category:'practical',kind:'reflection',level:'Internship experience',question:'Describe a task from an internship, lab, or team project where you had to learn something quickly. How did you approach it?',hint:'If you have not had an internship, use coursework, a personal project, or a hackathon example.',prompts:['Starting point','How you learned','Result','Lesson']},
 {id:'x4',category:'practical',kind:'reflection',level:'GitHub & collaboration',question:'How do you use Git and GitHub when working with other people on a codebase?',hint:'You can mention a real workflow, such as branches, pull requests, code review, and resolving a conflict.',prompts:['Your workflow','Code review','Handling conflicts','Team communication']},
 {id:'x5',category:'practical',kind:'reflection',level:'Hackathons & initiative',question:'Tell me about a time you built something under a tight deadline. How did your team decide what to prioritize?',hint:'A focused story about trade-offs and collaboration is more useful than claiming everything went perfectly.',prompts:['Goal & time limit','Prioritization','Your role','Outcome']},
 {id:'b1',category:'behavioral',kind:'reflection',level:'Communication',question:'Tell me about yourself and what kind of software engineering work interests you.',hint:'Keep it relevant to the role: your current focus, a useful example, and what you hope to do next.',prompts:['Present focus','Relevant example','Strengths','What is next']},
 {id:'b2',category:'behavioral',kind:'reflection',level:'Teamwork',question:'Tell me about a disagreement on a team. How did you work through it?',hint:'Choose a real, low-stakes example. Explain how you listened, found shared goals, and moved forward.',prompts:['Situation','Other perspective','Your action','Outcome']},
 {id:'b3',category:'behavioral',kind:'reflection',level:'Growth mindset',question:'What is a skill you are currently working to improve, and how are you making progress?',hint:'Pick a genuine area for growth and describe specific steps you are taking.',prompts:['Honest growth area','Concrete action','How you measure progress','Next step']},
 {id:'b4',category:'behavioral',kind:'reflection',level:'Motivation',question:'Why are you interested in this role, and what would you hope to contribute?',hint:'Connect the role to what you enjoy doing and support that with evidence from your experience.',prompts:['What interests you','Relevant evidence','Contribution','What you want to learn']},
 {id:'b5',category:'behavioral',kind:'reflection',level:'Resilience',question:'Describe a time something did not go to plan. What did you learn from it?',hint:'Take responsibility for your part and focus on what changed in your approach afterward.',prompts:['What happened','Your part','What you learned','How you changed']}
];
const sources = [
 {name:'Computer Science Engineering Interview Questions — Basic, Core, Advanced',publisher:'UPES · CSE interview categories, technical prompts & project discussions',url:'https://www.upes.ac.in/blog/computer-science/cse-interview-questions'},
 {name:'Computer Science Interview Questions',publisher:'InterviewBit · Core computer science preparation',url:'https://www.interviewbit.com/computer-science-interview-questions/'},
 {name:'Top 40+ Computer Science Interview Questions and Answers',publisher:'igmGuru · Common CS concepts and interview answers',url:'https://www.igmguru.com/blog/computer-science-interview-questions'},
 {name:'Computer Science Subjects Interview Questions',publisher:'GeeksforGeeks · Subject-wise CS fundamentals',url:'https://www.geeksforgeeks.org/computer-science-fundamentals/computer-science-subjects-interview-questions/'},
 {name:'47 Computer Science Interview Questions To Prepare',publisher:'Indeed · Technical and behavioral interview preparation',url:'https://www.indeed.com/career-advice/interviewing/computer-science-interview-questions'},
 {name:'15 Best Internships for BTech CSE Students',publisher:'UPES · Internship and practical exposure context',url:'https://www.upes.ac.in/blog/computer-science/internship-for-btech-cse-students'}
];
const STORAGE={user:'interviewCoachUser',progress:'interviewCoachProgress'};
let user=null, progress={}, activeFilter='all', quizItems=[], quizIndex=0, selectedOption=null, answered=false, sessionCount=0, toastTimer;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function load(){try{user=JSON.parse(localStorage.getItem(STORAGE.user));progress=JSON.parse(localStorage.getItem(STORAGE.progress))||{completed:[],practiceDates:[]}}catch{user=null;progress={completed:[],practiceDates:[]}}progress.completed ||= [];progress.practiceDates ||= []}
function save(){localStorage.setItem(STORAGE.user,JSON.stringify(user));localStorage.setItem(STORAGE.progress,JSON.stringify(progress))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(name){return name.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function showApp(){ $('#login-screen').classList.add('hidden');$('#app').classList.remove('hidden');$('#welcome-name').textContent=user.name.split(/\s+/)[0];$('#profile-button').textContent=initials(user.name);renderProgress();renderQuestions();renderSources();showView('overview')}
function showLogin(){ $('#login-screen').classList.remove('hidden');$('#app').classList.add('hidden') }
function showView(name){$$('.view').forEach(v=>v.classList.add('hidden'));const target=$(`#${name}-view`);if(target)target.classList.remove('hidden');const labels={overview:'Overview',practice:'Practice questions',progress:'My progress',sources:'Learning sources'};$('#crumb-current').textContent=labels[name]||'Overview';$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='practice')renderQuestions();if(name==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'})}
function completedCount(cat){return progress.completed.filter(id=>questions.find(q=>q.id===id)?.category===cat).length}
function streak(){const days=[...new Set(progress.practiceDates)].sort().reverse();if(!days.length)return 0;const today=new Date().toISOString().slice(0,10);let cursor=new Date(`${days[0]}T12:00:00`);if(days[0]!==today){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);if(days[0]!==yesterday.toISOString().slice(0,10))return 0;cursor=yesterday}let n=0;for(const d of days){if(d===cursor.toISOString().slice(0,10)){n++;cursor.setDate(cursor.getDate()-1)}else break}return n}
function renderProgress(){const total=progress.completed.length, pct=Math.round(total/questions.length*100),st=streak();$('#progress-percent').textContent=`${pct}%`;$('#progress-percent-large').textContent=`${pct}%`;$('#questions-completed').textContent=total;$('#progress-total').textContent=total;$('#streak-count').textContent=st;$('#progress-streak').textContent=st;$('#side-streak').textContent=`${st} day${st===1?'':'s'} streak`;$('#progress-ring').style.setProperty('--progress',`${pct*3.6}deg`);$('#progress-ring-large').style.setProperty('--progress',`${pct*3.6}deg`);for(const cat of Object.keys(categoryInfo)){const n=completedCount(cat),totalCat=questions.filter(q=>q.category===cat).length;const d=$(`#done-${cat}`),bar=$(`#bar-${cat}`);if(d)d.textContent=n;if(bar)bar.style.width=`${Math.round(n/totalCat*100)}%`}$('#progress-category-list').innerHTML=Object.entries(categoryInfo).map(([id,c])=>{const n=completedCount(id),nall=questions.filter(q=>q.category===id).length;return `<div class="progress-category-row"><span class="cat-dot ${c.dot}"></span><div class="progress-category-copy"><strong>${c.title}</strong><small>${nall-n} questions left to explore</small></div><span class="progress-track"><i style="width:${Math.round(n/nall*100)}%"></i></span><span class="progress-count">${n} / ${nall}</span></div>`}).join('')}
function renderQuestions(){const list=$('#question-list');if(!list)return;let filtered=questions.filter(q=>activeFilter==='all'||q.category===activeFilter);list.innerHTML=filtered.map((q,i)=>`<article class="question-row" data-question="${q.id}"><span class="question-number">${String(i+1).padStart(2,'0')}</span><div class="question-row-main"><h3>${esc(q.question)}</h3><span class="question-meta">${categoryInfo[q.category].title} · ${esc(q.level)} · ${progress.completed.includes(q.id)?'Practiced':'Ready to practice'}</span></div><span class="question-tag"><span class="cat-dot ${categoryInfo[q.category].dot}"></span>${esc(q.level)}</span><span class="question-row-arrow">↗</span></article>`).join('');$$('.question-row').forEach(row=>row.addEventListener('click',()=>startQuiz(row.dataset.question)))}
function renderSources(){$('#source-list').innerHTML=sources.map((s,i)=>`<a class="source-item" href="${s.url}" target="_blank" rel="noopener noreferrer"><span class="source-index">${String(i+1).padStart(2,'0')}</span><span class="source-info"><strong>${esc(s.name)}</strong><small>${esc(s.publisher)}</small></span><span class="source-arrow">↗</span></a>`).join('')}
function openCategory(cat){activeFilter=cat;$$('.filter-chip').forEach(c=>c.classList.toggle('active',c.dataset.filter===cat));showView('practice')}
function startQuiz(id){const selected=id?questions.find(q=>q.id===id):null;if(selected){quizItems=[selected]}else{let pool=questions.filter(q=>activeFilter==='all'||q.category===activeFilter);const untried=pool.filter(q=>!progress.completed.includes(q.id));if(untried.length)pool=untried;quizItems=pool.sort(()=>Math.random()-.5).slice(0,5)}quizIndex=0;sessionCount=0;$('#quiz-modal').classList.remove('hidden');document.body.style.overflow='hidden';renderQuizItem()}
function renderQuizItem(){const q=quizItems[quizIndex];selectedOption=null;answered=false;$('#quiz-category-label').textContent=categoryInfo[q.category].label;$('#quiz-number').textContent=String(quizIndex+1).padStart(2,'0');$('#quiz-total').textContent=String(quizItems.length).padStart(2,'0');$('#quiz-progress-line').style.width=`${Math.round((quizIndex)/quizItems.length*100)}%`;$('#question-type').textContent=q.kind==='mcq'?q.level.toUpperCase():q.level.toUpperCase();$('#quiz-title').textContent=q.question;$('#quiz-hint').textContent=q.hint||'';$('#quiz-hint').classList.toggle('hidden',!q.hint);$('#answer-feedback').classList.add('hidden');$('#answer-feedback').classList.remove('incorrect');$('#answer-options').classList.toggle('hidden',q.kind!=='mcq');$('#answer-options').innerHTML=q.kind==='mcq'?q.options.map((o,i)=>`<button class="answer-option" data-option="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join(''):'';$$('.answer-option').forEach(b=>b.addEventListener('click',()=>{if(answered)return;selectedOption=Number(b.dataset.option);$$('.answer-option').forEach(x=>x.classList.toggle('selected',x===b));$('#submit-answer').disabled=false}));$('#reflection-box').classList.toggle('hidden',q.kind!=='reflection');$('#reflection-answer').value='';$('#reflection-prompts').innerHTML=(q.prompts||[]).map(p=>`<span>${esc(p)}</span>`).join('');$('#submit-answer').classList.remove('hidden');$('#submit-answer').disabled=q.kind==='reflection';$('#submit-answer').textContent=q.kind==='reflection'?'Mark as practiced':'Check my answer';$('#next-question').classList.add('hidden');$('#quiz-score').textContent=`${sessionCount} answered`;$('#reflection-answer').oninput=e=>$('#submit-answer').disabled=e.target.value.trim().length<12}
function record(q){if(!progress.completed.includes(q.id))progress.completed.push(q.id);const d=new Date().toISOString().slice(0,10);if(!progress.practiceDates.includes(d))progress.practiceDates.push(d);save();sessionCount++;renderProgress()}
function submitAnswer(){const q=quizItems[quizIndex];if(answered)return;if(q.kind==='mcq'&&selectedOption===null)return;if(q.kind==='reflection'&&$('#reflection-answer').value.trim().length<12)return;answered=true;record(q);const feedback=$('#answer-feedback');if(q.kind==='mcq'){const ok=selectedOption===q.answer;feedback.textContent=(ok?'That’s right. ':'Good attempt. ')+q.explanation;feedback.classList.toggle('incorrect',!ok);$$('.answer-option').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(i===selectedOption)b.classList.add('incorrect')})}else{feedback.textContent='Nice work showing up for the practice. Review your answer: did you give a clear example, explain your part, and share what you learned?';feedback.classList.remove('incorrect')}feedback.classList.remove('hidden');$('#submit-answer').classList.add('hidden');$('#next-question').classList.remove('hidden');$('#next-question').innerHTML=quizIndex===quizItems.length-1?'Finish round <span>✓</span>':'Next question <span>↗</span>';$('#quiz-progress-line').style.width=`${Math.round((quizIndex+1)/quizItems.length*100)}%`;$('#quiz-score').textContent=`${sessionCount} answered`}
function nextQuestion(){if(quizIndex<quizItems.length-1){quizIndex++;renderQuizItem()}else{closeQuiz();renderProgress();renderQuestions();showToast(`Round complete — ${sessionCount} question${sessionCount===1?'':'s'} practiced.`)}}
function closeQuiz(){ $('#quiz-modal').classList.add('hidden');document.body.style.overflow='';renderProgress();renderQuestions() }
function showToast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),2800)}
$('#login-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);user={name:String(data.get('name')).trim(),email:String(data.get('email')).trim()};save();showApp()});$('#logout-button').addEventListener('click',()=>{localStorage.removeItem(STORAGE.user);showLogin()});$('#profile-button').addEventListener('click',()=>{localStorage.removeItem(STORAGE.user);showLogin()});$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('.category-link').forEach(b=>b.addEventListener('click',()=>openCategory(b.dataset.category)));$$('[data-view="practice"], [data-view="progress"], [data-view="sources"]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-open-category]').forEach(c=>c.addEventListener('click',()=>openCategory(c.dataset.openCategory)));$$('[data-action="start"]').forEach(b=>b.addEventListener('click',()=>startQuiz()));$('#filter-row').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;$$('.filter-chip').forEach(c=>c.classList.toggle('active',c===b));renderQuestions()});$('#submit-answer').addEventListener('click',submitAnswer);$('#next-question').addEventListener('click',nextQuestion);$('#skip-question').addEventListener('click',()=>{if(quizIndex<quizItems.length-1){quizIndex++;renderQuizItem()}else closeQuiz()});$$('[data-close="true"]').forEach(x=>x.addEventListener('click',closeQuiz));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#quiz-modal').classList.contains('hidden'))closeQuiz()});
load();if(user)showApp();else showLogin();
